name: cat_trivia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3 # https://pub.dev/packages/flutter_bloc
  retrofit: ^4.0.3 # https://pub.dev/packages/retrofit
  retrofit_generator: ^8.0.6 # https://pub.dev/packages/retrofit_generator
  dio: ^5.4.0 # https://pub.dev/packages/dio
  hive: ^2.2.3 # https://pub.dev/packages/hive
  hive_flutter: ^1.1.0 # https://pub.dev/packages/hive_flutter
  path_provider_windows: ^2.2.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1 # https://pub.dev/packages/hive_generator
  build_runner: ^2.4.7 # https://pub.dev/packages/build_runner


flutter:
  uses-material-design: true
